apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
  namespace: database
data:
  initdb.sql: |
          CREATE DATABASE bricks;
          USE bricks;
          CREATE TABLE highscore (score int);
          SELECT * FROM highscore;
          INSERT INTO highscore VALUES (0);
