apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-mysql
  namespace: database
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
