apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: secret-mysql
  namespace: database
spec:
  encryptedData:
    password: AgAY8N4mjLbUBMRIecg645a3zXCv73//a+np6B9QWU3YMOU3Ekr4tcqVQZZ3dH8Fa1k5tw7Jqm/IRjHHCdG6rpK3jRzUez8OcF7N2TW46FWyvXdO8CCRF9MY7QFXvY/1EYyMHZN8Oi02gJr8k1j/JPkURtirWLENfj6BrG34RiGHO/GphWjifGMfz+R4bYnNEjDVqRxP9xvc6dM+BPD4WwuDbwSCoxpwzOUIbPEeoHryws4jSmYGVgcXVe7E9UGTcJY+b1UIwZQ4x1HlLfEoyWQrxrzxGZKqPWwKvZYproJbpuZy4QeGpt/LHT/weGpww+Xdb9xYip4toWVahQbm7LRrkOvR1LwDwQfITP9GUgwnFGeNZKHM4aWok3CMWhn0IhuipCyYICVwI/MnW47fl3YJmArx6YZ/sNZrlnM0qkVwoiWFza+acFle8W2hSigw7FgMBcXKLN+YdkSUb7Kl1RkzLLKueFveM0EiKtc/zg+Xsms30jhCi3G9+kpaAbT+SlVK8bbHIvetms/nmgcN4id34wBuJedt9DV9vQSlw/nK063qzwcP+33iUypjgfBzCvvuw4+rsJ/Qq6cEND0hH6uQQlh9A+FNep/tgvD39G70lmIy2R/dIQrSHM1+/KUcc6EwMzqA+TT00AuyXiDMKzabO9lgk1b56PBU2mQvse2iYYs9raZ4Yr+RPV+oHKmPIiTc0ziStAqEJ53fH6zgGxRWkh8zsBd0z31q
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: secret-mysql
      namespace: database

